version: '3'
services:
  ghost:
    image: ghost:1-alpine
    ports:
      - 2368:2368
    restart: always
    environment:
      - database__client=mysql
      - database__connection__host=db
      - database__connection__user=root
      - database__connection__password=password
      - database__connection__database=ghost
    networks:
      - my-network
    depends_on:
      - "db"
  
  db:
    image: mysql:5.7.40
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      # - /home/felipe/trybe/pre-repo/docker-dia-3-exercicio:/var/lib/mysql
      - ./db-data:/var/lib/mysql
    networks:
      - my-network

networks:
  my-network: